### ISSUE TITLE
QueryArtworkWidget with Hero Widget not work

### ISSUE THREAD

**Issue by mstfkhazaal** [LucJosin/on_audio_query#66]
I use Hero widget with QueryArtworkWidget but not work

**Comment by LucJosin** [comment]
Hi @mstfkhazaal. I tried adding the `Hero` widget into `QueryArtworkWidget` but only works when 'pop()' the page. The problem is: To hero work with `FutureBuilder`(Method used to fetch the image) we need a `initialData` or the image won't animate. 

See [Hero widget working only when going back in Flutter](https://ishouldgotosleep.com/posts/hero-widget-working-only-when-going-back-in-flutter/)

So, the only way to animate is using `queryArtwork` and using your own(Or you can just copy&edit the `QueryArtworkWidget`) widget. You'll need to load/query the image first and then adding to `Hero` widget as a child.
